### ISSUE TITLE
Is there any update for Android?

### ISSUE THREAD

**Issue by lehoi2195** [cristianoccazinsp/react-native-zar-measure#2]
I've been working on a feature similar to your project. I've installed and used it on iOS, and it's fantastic how efficiently it works.
Do you have any plans to roll it out on Android as well? Thank you!

**Comment by cristianoccazinsp** [comment]
Hi Le,I’m no longer working on this, sorry about that!Also truth is, Android APIs were pretty bad compared to iOS when I wrote this, so it would be challenging. Not sure if it has improved since.Cristiano.On Jun 10, 2024, at 20:24, Le Hoi ***@***.***> wrote:﻿
I've been working on a feature similar to your project. I've installed and used it on iOS, and it's fantastic how efficiently it works.
Do you have any plans to roll it out on Android as well? Thank you!

**Comment by lehoi2195** [comment]
Thank you for your contributions, cristianoccazinsp.
